name: gamepad
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  # motion_sensors: ^0.1.0
  # galli_motion_sensors: ^0.0.3
  # webview_flutter: ^4.2.2 
  flutter_joystick: ^0.0.3
  sensors_plus: ^3.0.2
  socket_io_client: ^2.0.0
  vibration: ^1.8.1
  get: ^4.6.5
  get_storage: ^2.1.1
  video_player: ^2.2.5
  web_socket_channel: 
  file_picker:
  flutter_overlay_window: ^0.4.3
  firebase_core: ^2.15.0
  cloud_firestore: ^4.8.4
  permission_handler:
  peerdart:
  flutter_background:
  sdp_transform:
  # three_dart: ^0.0.16
  # flutter_neumorphic: ^3.2.0
  # vibration: ^1.7.5

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  fonts:
   - family: NeumorphicIcons
     fonts:
      - asset: fonts/NeumorphicIcons.ttf
